server:
  port: 9000
spring:
  application:
    name: "recommendation"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    lease-renewal-interval-in-seconds: 30
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "recommendation"
    description: "DemoApp recommendation Application"
    version: "1.0.0"