build:
  version: "1.0"

products:
  message: "Welcome to DemoApp products related prod APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@demoapp.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384