build:
  version: "3.0"

products:
  message: "Welcome to DemoApp products related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@demoapp.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
