build:
  version: "3.0"

recommendation:
  message: "Welcome to DemoApp recommendation related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@demoapp.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934