build:
  version: "1.0"

review:
  message: "Welcome to DemoApp review related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@demoapp.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721