build:
  version: "2.0"

review:
  message: "Welcome to DemoApp review related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@demoapp.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267