build:
  version: "3.0"

review:
  message: "Welcome to DemoApp review related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@demoapp.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932