server:
  port: 8085

spring:
  application:
    name: "ProductComposite"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

products:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000
    listOfServers: localhost:8080,localhost:8081

info:
  app:
    name: "ribbon"
    description: "DemoApp Composite Application"
    version: "1.0.0"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    lease-renewal-interval-in-seconds: 30
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/